### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by Shichimin** [Shichimin/furima_1295#9]
## フリマアプリのURL
https://furima-1295.herokuapp.com/

## Basic認証のIDとパスワード
ID: admin
Password: 2222

## 出品者用のメールアドレスとパスワード
Email: furitaro@hoge.com
Password: furitar0

## 購入者用のメールアドレスとパスワード
Email: furijiro@hoge.com
Password: furijir0

## 購入用カードの番号・期限・セキュリティコード
Number: 4242424242424242
EXP: 2/34
CVC: 123

**Comment by tec-camp** [comment]
Shichimin さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①新規出品した瞬間に、Sold Outが出てしまう
②購入した商品でも、「購入画面に進む」の表記があり、購入し続けられる形で遷移してしまう

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Shichimin** [comment]
minezakiさん、レビューありがとうございます！
ご指摘いただいた個所を修正いたしました！

> ①新規出品した瞬間に、Sold Outが出てしまう

商品に購入処理テーブルの情報が紐付いている場合にのみ、Sold Outを表示させるようにしました。

> ②購入した商品でも、「購入画面に進む」の表記があり、購入し続けられる形で遷移してしまう

商品に購入処理テーブルの情報が紐付いている場合、「購入画面に進む」を表示させないようにしました。

また、以下の修正を追加で行いました。
- すでに購入された商品の情報は出品者であっても再編集できないようにする
- 商品購入ページへアクセスできるユーザを制限（URLを直接指定した場合であっても、自分で出品した商品の購入ページへは遷移できないように修正）

お手数ですが、ご確認よろしくおねがいします！

**Comment by tec-camp** [comment]
Shichimin さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。

**Comment by Shichimin** [comment]
minezakiさん、LGTMありがとうございます！

このままフリマアプリの追加実装を進めていこうとようと思います！
引き続き、よろしくお願いいたします！
